Linear algebra update
Chrismarsh/CHM pull request #139
Opened 2020-09-15 21:09 UTC by kevinrichardgreen

- Change underlying library to Trilinos
- Isolate linear algebra to its own class

Also:
- organize third party compilation
- clean up compiler warnings for src/ files (from gcc at least)

2020-09-16 15:40 UTC, Chrismarsh requested changes

2020-09-16 21:15 UTC, Chrismarsh commented on src/mesh/triangulation.cpp
> +  std::vector<boost::mpi::request> reqs;
These all need to be protected in non MPI mode

2020-09-17 15:49 UTC, kevinrichardgreen commented on src/modules/PBSM3D.cpp
> +    auto suspension_rhs_max = suspension_NNP->getRhsMax();
Yes. Threshold set to a small value. If the RHS=0, we don't need to solve. Saves time in that the preconditioner does not get computed on this step.

2020-09-17 17:26 UTC, Chrismarsh approved these changes

2020-09-17 17:26 UTC, merged